backend:
  name: git-gateway
  repo: "Justin-way/Justin-way.github.io" # blog 存放在 Github repo 的位置
  branch: "main" # 分支
  site_url: "https://github.com/Justin-way/Justin-way.github.io" # 你的網站網址

media_folder: "static/img" # 存放多媒體的資料夾
public_folder: "/img"
locale: "zh_Hant" # 語系 https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-locales/src

collections: # https://www.netlifycms.org/docs/configuration-options/#collections
  - name: "posts"
    label: "文章"
    folder: "blog/exampleSite/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "草稿", name: "draft", widget: "boolean" }
      - { label: "描述", name: "description", widget: "string" }
      - { label: "分類", name: "categories", widget: "list" }
      - { label: "內容", name: "body", widget: "markdown" }
      scope:
        path: "blog/exampleSite/content/blog/"
        pattern: ".md"
        values:
        type: "post"
